site_name: Techniques de l'informatique du Cégep de Victoriaville
site_author: Étienne Rivard
theme:
  name: material
  custom_dir: overrides
  language: fr
  features:
    - content.code.copy
  logo: assets/logo32x32.png
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - search

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/alltarget.js

nav:
  - 'Page principale': 'index.md'
  - 'Demander du tutorat': 'tutorat.md'
  - 'Équipe': 'equipe.md'
  - 'Stages':
      - 'Pour les élèves': 'stages-eleve.md'
      - 'Pour les employeurs': 'stages.md'

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

docs_dir: 'wiki'
site_dir: 'www'
use_directory_urls: True
